[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name="multilingual_smile"
version="0.1.0"
description = "Multilingual SMILE: A Multilingual Extension of the Composite Lexical-Semantic SMILE Metric for LLM-Generated Response Evaluation"
authors = [
    {name="Sai Teja Sunku"},
    {name="Ronak Wani"}
]
readme = "README.md"
requires-python = ">=3.9"
license = { file = "LICENSE.txt" }
dependencies = [
    "numpy",
    "scikit-learn",
    "nltk",
    "tqdm",
    "transformers",
    "openai",
    "requests",
    "sentence-transformers",
    "huggingface-hub",
    "bert-score",
    "rouge-score",
    "moverscore @ git+https://github.com/AIPHES/emnlp19-moverscore.git",
    "bleurt @ git+https://github.com/google-research/bleurt.git",
    "pyemd",
    "evaluate"
]

[tool.setuptools]
py-modules = ["main"]

[tool.setuptools.packages.find]
include = ["smile*", "pyscripts*"]
exclude = ["sample_data*"]

[project.scripts]
multilingual-smile = "main:main"
